### ISSUE TITLE
Loading dynamic size

### ISSUE THREAD

**Issue by gentle9** [swiety85/angular2gridster#256] opened 2018-06-08 08:29 UTC
It seems that I am having the same problem as I had in this issue #116 but this time with the responsive size instead of position.

When dynamic loading the widgets like in this example the size w / h is loaded instead of the responsive sizes (wXl, ...).

```
widgets:any = [];
widgetsTemp:any = [
    {
        x: 0, y: 0, w: 1, h: 2, wSm: 2, hSm: 3, wMd: 2, hMd: 3, wLg: 2, hLg: 3, wXl: 2, hXl: 3, xSm: 0, ySm: 0, xMd: 0, yMd: 0, xLg: 0, yLg: 0, xXl: 5, yXl: 0,
        title: 'Basic form inputs 1',
        content: 'Widget content'
    }
]
...
this.widgets = this.widgetsTemp;
...
```

Edit: I am using the current version 6.0.0-rc.1

**Comment by swiety85** [comment] 2018-06-14 20:14
Hi,
I can't reproduce your problem. Did you set `responsiveSizes: true` in your gridster options? This option is required to use responsive size properties.
You can provide code sandbox were the problem is visible:

[![Edit Angular2gridster demo](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/w77q2rqll)

**Comment by swiety85** [comment] 2019-08-20 21:42
Since there is no answer, I will close this issue.

**Closed by swiety85** 2019-08-20 21:42 UTC
