### ISSUE TITLE
error when building with ng build --prod

### ISSUE THREAD

**Issue by wweitzel** [swiety85/angular2gridster#193] opened 2018-02-15 19:28 UTC
My app will build successfully using `ng build --prod` but when i load the app in the browser I am confronted with the error `r.Observable.merge is not a function`. Screenshots below:

![image](https://user-images.githubusercontent.com/17417149/36276477-19424e76-125c-11e8-94ae-6151cf47c63e.png)

Then clicking on that error takes me to

![image](https://user-images.githubusercontent.com/17417149/36276562-612a1f5c-125c-11e8-8a17-74e733ac5f09.png)

The app doesn't have this error when built with `ng build` or `ng build --aot=true`. Only has the error when built with `ng build --prod`

**Comment by rudzikdawid** [comment] 2018-02-15 19:33
content of your `package.json` ? link to repository?
any help to reproduce the error?

**Comment by swiety85** [comment] 2018-02-15 21:18
Can you add `import 'rxjs/add/operator/merge';` on top of the component that renders gridster and check if problem still occure?

**Comment by wweitzel** [comment] 2018-02-15 22:23
@swiety85 adding `import 'rxjs/add/operator/merge` has solved the problem. Thank you!

**Comment by swiety85** [comment] 2018-03-10 23:32
Fixed in v1.3.0

**Comment by Vevl** [comment] 2018-06-18 14:21
Hello @swiety85  I have just a little question about this bug. Im using angular v5.2.3 and CLI v1.6.7 so as I read in your comments you recommend v5.0.0 of Angular2gridster. 
But i dont think its working with --prod build. It dont throw any error while build but when i run my app loading of grid system take a bigger moment and after that it is all bugged the items has not right sizes and app cant work anymore. 
Anyway I tried all options of importing "merge" and other advices from stuck overflow but nothing helps.

![obrazok](https://user-images.githubusercontent.com/35180926/41541768-857d0ece-7313-11e8-8009-ce3b9b54338a.png)

Thank you for your respond.

**Comment by wweitzel** [comment] 2018-07-02 14:59
It seems I am now getting this error again as well. It seems specific to using the build optimizer. When building the project with --aot, there are no problems. Only when building the project with the --build-optimizer flag.

**Comment by swiety85** [comment] 2018-07-02 19:57
Hi,
I can't reproduce your problem.
To reproduce it I created the sample project with angular CLI v1.7.4, that uses angular 5.2.0. I installed angular2gridster v5.0.0 and place the gridster in the app component (from demo).
I tried builds with  --prod and --dev and I got no error nor in the build neither in the browser console.
@wweitzel I played with `--build-optimizer` param and it also works fine for me. I tried also to run `--build-optimizer` without `--aot` but I got: "The `--build-optimizer` option cannot be used without `--aot`".
Please provide me more details.
@Vevl Are you sure you use angular2gridster v5.0.0? The stack trace does not look like this version.

**Comment by Vevl** [comment] 2018-07-03 16:23
Hello, thanks for your response @swiety85 yes im pretty sure that iave v5.0.0, maybe i made some mistake in my code but cant solve it. Do you think the problem should be in lazy loading? i provide gridster in my lazy loaded dashboard module like this: 

import { GridsterModule } from 'angular2gridster';
imports:  [ GridsterModule.forRoot() ...]

after that i just import ->
 import { GridsterComponent, IGridsterOptions, IGridsterDraggableOptions }  from 'angular2gridster';  
 in my component which render grid.

I dont know how to introduce you more my situation. I think im doing something wrong but dont know what. In situation where i build my app like this ->
ng build   - everything works fine but in build like this ->
ng build --prod --build-optimizer     - grid doesnt work.

Also in my project im using libraries like this -> https://lodash.com/docs#merge  and mergewith. Maybe this makes some mess?

Thank you very much.

**Comment by Vevl** [comment] 2018-08-17 06:04
Hey, @swiety85  just wanna let you know that I update my app to angular 6 and everything works fine, with or without --prod or --prod --build-optimizer.

**Comment by swiety85** [comment] 2018-10-09 19:11
Please use the newest version: v6.+.

**Closed** 2018-10-09 19:10 UTC
Labels: bug, build
