### ISSUE TITLE
position initial

### ISSUE THREAD

**Issue by julianodev** [swiety85/angular2gridster#216] opened 2018-03-28 22:42 UTC
Hello,

I would like to know how do I set a starting position for a gridster-item? So I can save this information and save the last user configuration.

Thank you

**Comment by rudzikdawid** [comment] 2018-03-29 07:42
https://github.com/swiety85/angular2gridster/blob/master/demo/src/app/app.component.ts

```
widgets: Array<any> = [
        {
            x: 0, y: 0,
            w: 1, h: 2,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 1'
        },
        {
            x: 1, y: 0, w: 3, h: 1,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 2'
        },
        {
            x: 1, y: 1, w: 2, h: 1,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 3'
        },
        {
            x: 3, y: 1, w: 1, h: 2,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs 4'
        },
        {
            w: 1, h: 2,
            dragAndDrop: true,
            resizable: true,
            title: 'Basic form inputs x'
        }
    ];
```
Array `widgets` contains all information about `gridster-item` position.
In prod you need load/read this data from some `REST` using `xhr` (is not the only solution)
And after widgets maniuplations (moving resizing) you need keep this mutated Array `widgets` for example send it to `REST` or save in `localStorage`

http://dawid.ru/workspace/something
here is example using `localStorage`
you can move/resize widget and after refresh state  is recovered

**Comment by julianodev** [comment] 2018-03-29 11:14
Hello,

imagining that I have 2 gridster-item.

and within them 2 components

<app-chart1 # chart1> </ app-chart1> and

<app-chart2 # chart2> </ app-chart2>

I wanted to call them on my app.component.ts

@ViewChild ('chart1') chart1;

afterViewInit () {
 this.chart1.item.x = 0;
 this.chart1.item.y = 0;
 this.chart1.item.w = 1;
 this.chart1.item.h = 2;

}

That should work, right?

Thanks 🍡

**Comment by julianodev** [comment] 2018-03-29 11:52
because then the user can position the items in the way that he thinks best and I save this information in an api rest, so he can refresh and the items will self position :(

**Comment by rudzikdawid** [comment] 2018-03-29 12:07
imagine that you move one `gridster-item` and it push other siblings changing theirs positions.
You need call siblings to read they current position and save it ? it sounds very messy.
 `gridster-item` affect each others thats why they are not independent. The simplest way is interprete all  `gridster-item` as group and controll theirs state as group.

**Comment by dmend078** [comment] 2018-03-29 13:16
I am trying to do the same thing. I am saving the x and y positions (plus the w and h) but when it loads the items are placed in a different position. Let me explain. The items get placed in the same position that the user save them, only if they save them by filling the first row. For example: 
XX
will be:
XX
But the problem is>
X
X
will be in reload like:
XX 
This is not right now like a big deal. But I will like to know if this is the supposed behavior or this is something that can be fixed?

**Comment by rudzikdawid** [comment] 2018-03-29 13:42
@dmend078 could you prepare example? link to repo?
Which version of `angular2gridster` do you use?
Can you reproduce this issue in my example? http://dawid.ru/workspace/something
after moving/resiznig widgets press F5 to refresh. State should restore

**Comment by julianodev** [comment] 2018-03-29 13:49
![gridster](https://user-images.githubusercontent.com/20190078/38092429-9baf9ff0-333e-11e8-87f8-118cafb5dbec.gif)

I just wanted to move the items and save their position in the localstorage so that when refresh they continue in the last position that the user left

is possible ?

**Comment by rudzikdawid** [comment] 2018-03-29 13:54
@julianodev yes it's possible http://dawid.ru/workspace/something here is example
you can move/resize widget after refresh last state is restoring from `loclaStorage`

source repo: https://github.com/rudzikdawid/material2-start/tree/patients/src/app/workspace/something

**Comment by dmend078** [comment] 2018-03-29 14:04
@rudzikdawid  your tutorial does exactly what I need. I will need to compare to see the problem. Thank you.

**Comment by julianodev** [comment] 2018-03-29 14:05
thanks :)

**Comment by dmend078** [comment] 2018-03-29 14:16
@rudzikdawid  just to be sure. 
It has to be due to the FlexLayoutModule? 
Because my code looks exactly the same, except for the FlexLayoutModule. I don't have that.

**Comment by rudzikdawid** [comment] 2018-03-29 14:19
@dmend078 in 1 line of code https://github.com/rudzikdawid/material2-start/blob/patients/src/app/workspace/something/something.component.html
i used `fxLayout="column" fxFlexFill` thats why i need `FlexLayoutModule`
but i think that it's not important in our case

**Comment by swiety85** [comment] 2018-03-29 14:36
Hi @julianodev,
I would say that the problem could be the `afterViewInit` in which you set changes for items. As far as I know, this lifecycle hook doesn't trigger change detection. Why don't you use `ngOnInit`? If this is not an option, try `ngAfterContentInit`.
Give me a hint if it solves your problem.

**Comment by dmend078** [comment] 2018-03-29 15:22
@rudzikdawid thank to your tutorial I know what was happening. I am not saving the xXl and yYl position right. The problem is that when the itemChange fires the widget (element of the array that contains the data for the gridster-item) haven't updated the position xXl and yXl.

**Comment by julianodev** [comment] 2018-03-29 21:24
Hi @swiety85 ,

I put a simple project where I'm just trying to move the items and put them in the localstorage can help me please?

I would move them and by giving F5 continue in the position I had left.

I added you as a contributor.

Thank you very much for your attention.

https://github.com/julianodev/gridster-demo

**Comment by swiety85** [comment] 2018-03-30 14:27
I've made merge request in your demo project with some possible solution to store gridster items config in localStorage: https://github.com/julianodev/gridster-demo/pull/1.

**Comment by julianodev** [comment] 2018-03-30 14:51
thank you for the effort and time dedication and congratulations for your excellent work my sincere thank you. Embrace your Brazilian friend :)

**Closed** 2018-03-30 14:58 UTC
